#
# <https://github.com/KFERMercer/luci-app-nezha-agent>
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# Copyright (C) 2020 [CTCGFW] Project OpenWRT
# 
# THIS IS FREE SOFTWARE, LICENSED UNDER GPLv3.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-nezha-agent
LUCI_TITLE:=LuCI support for nezha agent
LUCI_DEPENDS:=+nezha-agent
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=1
PKG_MAINTAINER:=<https://github.com/KFERMercer/luci-app-nezha-agent>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
