#!/bin/sh /etc/rc.common
USE_PROCD=1

START=90
STOP=10

enabled="$(uci get nezha-agent.config.enabled)"
host="$(uci get nezha-agent.config.host)"
secret="$(uci get nezha-agent.config.secret)"

start_service() {
        stop_service
        [ "$enabled" == "1" ] || exit 0
        procd_open_instance
        procd_set_param command /usr/bin/nezha-agent -s "${host}" -p "${secret}"
        procd_set_param respawn
        [ -e /proc/sys/kernel/core_pattern ] && {
                procd_set_param limits core="unlimited"
        }
        procd_close_instance
}

stop_service() {
        service_stop "/usr/bin/nezha-agent"
}

start() {
        start_service
}

stop() {
        stop_service
}