#!/bin/sh /etc/rc.common

START=90
STOP=10

enabled="$(uci get nezha-agent.config.enabled)"
host="$(uci get nezha-agent.config.host)"
secret="$(uci get nezha-agent.config.secret)"

start() {
	stop
	[ "$enabled" == "1" ] || exit 0
	nezha-agent -s "${host}" -p "${secret}" >/dev/null 2>&1 &
}

stop() {
	killall nezha-agent >/dev/null 2>&1
}
